### ISSUE TITLE
Shameless promotion (2018)

### ISSUE THREAD

**Issue by omermar** [antoineallard/networkspapers#2]
Hi and thank you for creating this very useful database!
In the description it writes that collection started in 2017, for papers with 'networks' in their title.
I've noticed that a paper of mine from February 2018 titled "Predicting species emergence in simulated complex pre-biotic networks" is not on the list and I think it should be because it is relevant for network science.
It's DOI is: [https://doi.org/10.1371/journal.pone.0192871](https://doi.org/10.1371/journal.pone.0192871) 
What do you think?

**Comment by antoineallard** [comment]
Hi Omer, thank you for your interest! Normally, I would try to honor the "New" as much as possible, but I actually needed a fifth article to complete today's feed. So there you go! Thank you for reaching out. Best.
